# Site settings
title: nan
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Keep Hungry Keep Foolish
baseurl: "/luojia-nan" # the subpath of your site, e.g. /blog/
url: "https://luojia-nan.github.io" # the base hostname & protocol for your site
twitter_username: null
github_username:  null

# Build settings
markdown: kramdown
